RpgAplication/RpgApplication/Controllers/CharacterCreationController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using RpgApplication.Areas.Identity.Data;
using RpgApplication.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RpgApplication.Controllers
{
    public class CharacterCreationController : Controller
    {
        private readonly UserManager<UserModel> _userManager;
        private readonly DatabaseContext _context;
        public CharacterCreationController(UserManager<UserModel> userManager, DatabaseContext context)
        {
            _userManager = userManager;
            _context = context;
        }
        public IActionResult Index()
        {
            List<MistbornCharacterSheetModel> MyCharacters = _context.MistbornCharacters.Where(x => x.UserName == _userManager.GetUserName(User)).ToList();
            ViewBag.MyCharacters = MyCharacters;
            return View();
        }
        [HttpPost]
        public IActionResult Index(string Id)
        {
            return RedirectToAction(nameof(CharacterSheet),new {CharacterId= int.Parse(Id) });
        }
        public IActionResult CharacterSheet(int CharacterId)
        {
            MistbornCharacterSheetModel model = _context.MistbornCharacters.First(x => x.Id == CharacterId);
            return View(model);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(MistbornCharacterSheetModel model)
        {
            model.UserName = _userManager.GetUserName(User);
            model.UserId = _userManager.GetUserId(User);
            _context.MistbornCharacters.Add(model);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

RpgAplication/RpgApplication/Controllers/GamesController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RpgApplication.Areas.Identity.Data;
using RpgApplication.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.SignalR;
using Microsoft.JSInterop;
using Microsoft.AspNetCore.SignalR.Client;

namespace RpgApplication.Controllers
{
    public class GamesController : Controller
    {
        private readonly UserManager<UserModel> _userManager;
        private readonly DatabaseContext _context;
        private readonly IJSRuntime _jSRuntime;
        public static HubConnection HubClient { get; set; }
        public GamesController(UserManager<UserModel> userManager, DatabaseContext context, IJSRuntime jSRuntime)
        {
            _userManager = userManager;
            _context = context;
            _jSRuntime = jSRuntime;
        }
        public IActionResult Index()
        {
            ViewBag.IsAdmin = User.IsInRole("Administrator");
            return View(_context.Games);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpGet("ShowGame/{Id}")]
        public async Task <IActionResult> ShowGame(string Id)
        {
            var CurrentGame = _context.GameMessages
               .Include(x => x.User)
               .ThenInclude(x => x.Characters)
               .Where(x => x.GameId == Id).ToList();

            if (HubClient is null) 
                HubClient = new HubConnectionBuilder().WithUrl(new Uri("http://localhost:6390/chatHub"))
                    .Build();

            if (HubClient.State==HubConnectionState.Disconnected)
                await HubClient.StartAsync();

            HubClient.On<string,string>("ReceiveMessage", (user,message) =>
            {
                CurrentGame.Add(new GameMessages { GameId = Id, Message = message, FromUserId = user, MessageDate = DateTime.Now });
            });

            GameMessages myMessge = new GameMessages() { GameId = Id };
            ViewBag.Messages = CurrentGame;
            ViewBag.UserName = _userManager.GetUserName(User);
            string userId = _userManager.GetUserId(User);
            bool allowedUser = _context.GameUsers.Any(
                x => x.GameId==Id && x.UserId == userId);
            ViewBag.Allowed = allowedUser;
            return View(myMessge);
        }
        [HttpPost]
        public async Task<IActionResult> AddMessage(string GameId, string message, int Roll, int Dices)
        {
            Random rnd = new Random();
            int succeses = 0;
            GameMessages model = new GameMessages()
            {
                GameId = GameId,
                Roll = Roll,
                Dices = Dices
            };
            for(int i=0;i<Dices;i++)
            {
                var result = rnd.Next(1, 11);
                if (result == 10) succeses += 2;
                else if (result + Roll > 9) succeses += 1;
                else if (result==1) succeses -= 1;
            }
            if (Dices != 0 || Roll != 0)
                message = message + " [Wynik rzutu: " + succeses.ToString() + "]";
            model.Message = message;
            model.FromUserId = _userManager.GetUserId(User);
            model.MessageDate = DateTime.Now;
            _context.GameMessages.Add(model);
            _context.SaveChanges();
            await HubClient.SendAsync("SendMessage", model.FromUserId, model.Message);
            return RedirectToAction(nameof(ShowGame), new { Id = model.GameId });
        }
        [HttpPost]
        public IActionResult Create(GameModel model)
        {
            model.Id = Guid.NewGuid().ToString();
            _context.Games.Add(model);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public IActionResult AddUserToGame(string Id, string warning = "")
        {
            List<MistbornCharacterSheetModel> PlayersThatCanBeAdded = _context.MistbornCharacters.Where(x => x.GamesId != Id).ToList();
            ViewBag.Players = PlayersThatCanBeAdded;
            ViewBag.GameId = Id;
            ViewBag.Warning = warning;
            return View();
        }
        [HttpPost]
        public IActionResult AddUserToGamePost(string Id, string GameId)
        {
            MistbornCharacterSheetModel SelectedCharacter = _context.MistbornCharacters.FirstOrDefault(x => x.Id == int.Parse(Id));
            _context.MistbornCharacters.FirstOrDefault(x => x.Id == int.Parse(Id)).GamesId = GameId;
            var selectedUserId = _context.Users.FirstOrDefault(x => x.Id == SelectedCharacter.UserId).Id;
            bool flag = true;
            foreach (var item in _context.GameUsers)
            {
                if (item.GameId == GameId && item.UserId == selectedUserId)
                    return RedirectToAction(nameof(AddUserToGame),
                        new { Id = GameId, warning = "Ten użytkownik uczestniczy już w tej grze" });
            }
            if (flag == true)
            {
                GameUser player = new GameUser();
                player.GameId = GameId;
                player.UserId = selectedUserId;
                _context.GameUsers.Add(player);
                _context.SaveChanges();
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

RpgAplication/RpgApplication/Views/Games/AddUserToGame.cshtml
@model RpgApplication.Models.MistbornCharacterSheetModel

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int selectedValue = 0;
    SelectList List = new SelectList(ViewBag.Players, "Id", "CharacterName", selectedValue);
    string GameId = ViewBag.GameId;
}
<div class="card text-white bg-dark mt-5 my-5 mx-auto opacity-card" style="width: 25rem;">
    <div class="card-body">
        <h3 class="card-title"> Dodaj Gracza do Gry</h3>
        <div class="row">
            <div class="col-sm">
                <form asp-action="AddUserToGamePost" asp-route-GameId="@GameId">
                    <div class="form-inline my-3">
                        <label asp-for="CharacterName" class="control-label mr-5 ml-2 my-3"></label>
                        <select asp-items="@(List)"
                                class="form-control" asp-for="Id">
                            <option value="wybierz">---Wybierz---</option>
                        </select>
                    </div>
                    @if (@ViewBag.Warning != "")
                    {
                        <div class="alert alert-danger font-weight-bolder">@ViewBag.Warning</div>
                    }
                    <div class="form-group align-items-center">
                        <input type="submit" value="Dodaj" class="btn btn-secondary" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

RpgAplication/RpgApplication/Views/Games/Create.cshtml
@model RpgApplication.Models.GameModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="card text-dark text-center mt-5 mx-auto opacity-card">
    <img class="card-img"
         src="https://raw.githubusercontent.com/vicberg/Roll20-Warhammer-4e-Character-Sheet/master/background.jpg"
         alt="Card image">
    <div class="card-img-overlay">
        <h2 class="card-title">Tworzenie Gry</h2>
        <div class="row justify-content-center">
            <div class="col-2">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="GameName" class="control-label"></label>
                        <input asp-for="GameName" class="form-control" />
                        <span asp-validation-for="GameName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="PhotoURL" class="control-label"></label>
                        <input asp-for="PhotoURL" class="form-control" />
                        <span asp-validation-for="PhotoURL" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-secondary" />
                    </div>
                </form>
            </div>
        </div>
        <div>
            <a asp-action="Index">Back to List</a>
        </div>
    </div>
</div>




@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RpgAplication/RpgApplication/Views/Games/Index.cshtml
@using Microsoft.AspNetCore.Identity

@model IEnumerable<RpgApplication.Models.GameModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutNoOverFlow.cshtml";

}
<div class="text-white">
    <h2 class="card-title">Gry</h2>
    <table class="table text-white">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.GameName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PhotoURL)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                @if (ViewBag.IsAdmin == true)
                {
                    <td>
                        <a style="color:inherit" asp-action="AddUserToGame" asp-route-Id="@item.Id">@Html.DisplayFor(modelItem => item.GameName)</a>
                    </td>
                }
                else
                {
                    <td>
                        @Html.DisplayFor(modelItem => item.GameName)
                    </td>
                }
                <td>
                    <a href="/ShowGame/@item.Id">
                        <img width="100" height="100" src="@Url.Content(item.PhotoURL)" />
                    </a>
                </td>

            </tr>
            }
        </tbody>
    </table>
</div>
@if (ViewBag.IsAdmin == true)
{
    <a style="color:white" asp-action="Create">Dodaj nową grę</a>
}

RpgAplication/RpgApplication/Views/Games/ShowGame.cshtml
@model RpgApplication.Models.GameMessages
@{
    ViewData["Title"] = "ShowGame";
    Layout = "~/Views/Shared/_LayoutNoOverFlow.cshtml";
    List<RpgApplication.Models.GameMessages> ListofMessages = ViewBag.Messages;
}
<head>
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="richtext.min.css">
    <link rel="stylesheet" href="~/css/game.css">
</head>
<body>
    <a class="card-title text-white" href="#pageDown" style="font-size: 1.5em">Trwająca sejsa</a>
    <div id="AllMessages">
        @for (int i = 0; i < ListofMessages.Count; i++)
        {
            <div class="row mx-5">
                @{
                    var PostingUser = ListofMessages[i].User.Characters.FirstOrDefault();
                }
                <div class="col-sm my-4 mx-5">
                    <div class="card text-white text-left" style="min-height: 18rem;">
                        <div class="card-header" style="background-color:#b2bec3">@ListofMessages[i].MessageDate</div>
                        <div class="card-body" style="background-color: #636e72">
                            <h5 class="card-title">@PostingUser.CharacterName</h5>
                            <p class="card-text">@ListofMessages[i].Message</p>
                        </div>
                    </div>
                </div>
                <div class="my-4 mx-5">
                    <div class="card text-white text-center" style="min-height: 10rem;min-width: 10rem">
                        <div class="card-body" style="background-color: #636e72;">
                            <div class="row justify-content-center">
                                <a asp-controller="CharacterCreation" asp-action="CharacterSheet" asp-route-CharacterId="@PostingUser.Id">
                                    <img class="rounded mx-auto d-block center "
                                         width="100" height="100"
                                         src="@Url.Content(PostingUser.CharacterAvatarURL)"/>
                                </a>
                            </div>
                            <div class="row justify-content-center text-white">
                                @ListofMessages[i].User.UserName
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
    @if (@ViewBag.Allowed)
    {
    <form asp-controller="Games" asp-action="AddMessage" method="post"
          asp-route-GameId="@Model.GameId" asp-route-message="@Model.Message" asp-route-Dices="@Model.Dices" asp-route-Roll="@Model.Roll" class="mx-5">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div id="pageDown" class="row my-5 mx-5">
            <div class="col-sm">
                <textarea class="form-control text-white" style="background-color: #636e72;" placeholder="Tu możesz pisać..." asp-for="Message" rows="8"></textarea>
            </div>
            <div class="card ml-4" style="min-height: 10rem;min-width: 10rem; background-color: #636e72">
                <div class="card-body" >
                    <label asp-for="Dices" class="control-label text-white"></label>
                    <input asp-for="Dices" class="form-control" />
                    <label asp-for="Roll" class="control-label text-white "></label>
                    <input asp-for="Roll" class="form-control" />
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm">
                <input class="btn btn-light text-white" style="background-color: #636e72" type="submit" id="sendButton" value="Napisz" />
            </div>
        </div>
    </form>
    }
    <script src="~/js/chat.js"></script>
</body>